language: clojure
before_deploy:
- lein ring uberjar
deploy:
  provider: releases
  api_key:
    secure: Xq/KWIa/XuX3cgu1/xgcMx1qka+I2bEAVDu9pqruXGQ9oMEgSdwUDwt1dx+ykgqUy+Zi5D+GHUQJ8ygQBNdrDPElEEcyhTWHSRog05lmYn5jqPM74Y1dhMX+LKBfXmNu9dIqMvhpatwcTEu9klIsK6a2LKqV5EgXoyh7UXKFzDFMDFKDNzSJ2kTaQ9d0UQTLEJP/rpkFOpwT29ggTjw56IYNi+BNvinjcYmGdKdnzfL6dW/pH0+SrdV4NsvenRtuu3Ics6goUKyRtGXYSFeYB7kfHYLFK7M5fK/btscki6Gi2pK02clURVWwXZGjDBzuICyez0T5WiBTlQh/M9xioc9BjhOWLn01sdUbqGNYkywul3NbqHq/KPq7rvjCLnEtHalJPQ/lDDNyK3mHynkb8mMPYNFb8KgFezC84nHnf7u+SNX7wymIACtqvSc9BDsWAvpKCFnjoNtKZccOVdJ3jg1SVCEZ9TCIn6nrnkgdKo6QgVgHIkqZk51I1BaYi3gmKbhS4y8m6gr/l83OzY7WYb8I/fHuti77v9Jh+Rb4H56/lSnK0s0A6eWNntzDupT0HvxeEsestqD9YWN40FfvZtjxPKvrWyy+YXhoUAcbDlanBZzNXsAVKrScaW0R2qJDseyVoClQmpnhV2Ovao8i+QiD9rSCE/FT1z9eSaH8WiI=
  file: $(ls target/greenyet-*-standalone.jar)
  skip_cleanup: true
  on:
    all_branches: true
